# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: v-aprozo

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'find files -type f | xargs'

- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: |
      /**/*
      !/**/*.css

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'find files -type f | xargs'


